() => {
  window.coffeeBase=new URL(window.location.pathname.replace(/\/?$/,'/'),location.origin);
  window.coffeeCsrf='';window.coffeeReviewed=false;window.coffeeConnected=false;window.coffeeRevision=-1;let connected=false,seen=-1,last=Date.now(),busy=false;
  const connectionStatus=()=>document.getElementById('connection-status');
  function gate(ok){connected=ok;window.coffeeConnected=ok;if(!ok)window.coffeeReviewed=false;if(connectionStatus())connectionStatus().textContent=ok?'Disponibilidad de la demo actualizada':'Disponibilidad sin actualizar. Puedes revisar el último menú recibido; espera para consultar o guardar.';
    for(const id of ['chat-submit','chat-manual','admin-save','admin-review']){const b=document.querySelector('button#'+id+',#'+id+' button');if(b)b.disabled=!ok||(id==='admin-save'&&!window.coffeeReviewed)||(id.startsWith('chat-')&&(ticket||sending));}}
  function filter(){const term=(document.getElementById('menu-filter')?.value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const category=document.getElementById('menu-category')?.value||'';
    document.querySelectorAll('.menu-card').forEach(card=>{const name=card.dataset.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'');card.hidden=!(name.includes(term)&&(!category||card.dataset.category===category));});
    document.querySelectorAll('.menu-category').forEach(section=>{section.hidden=!Array.from(section.querySelectorAll('.menu-card')).some(card=>!card.hidden);});
    const cards=Array.from(document.querySelectorAll('.menu-card')),visible=cards.filter(card=>!card.hidden).length;
    const count=document.getElementById('menu-count');if(count)count.textContent=(term||category)?visible+' de '+cards.length+' bebidas · Filtros activos':cards.length+' bebidas en el menú · Todas las categorías';
    const empty=document.getElementById('menu-empty');if(empty)empty.hidden=visible>0;}
  document.addEventListener('click',e=>{if(e.target.closest('#menu-reset')){document.getElementById('menu-filter').value='';document.getElementById('menu-category').value='';filter();}});
  async function snapshot(){if(busy)return;busy=true;try{const r=await fetch(new URL('api/menu',window.coffeeBase));if(!r.ok)throw Error();const d=await r.json();window.coffeeClockOffset=d.server_time-Date.now();const node=document.getElementById('coffee-menu');if(node){const old=document.getElementById('menu-filter')?.value||'';const category=document.getElementById('menu-category')?.value||'';node.innerHTML=d.html;document.getElementById('menu-filter').value=old;document.getElementById('menu-category').value=category;filter();}seen=d.revision;window.coffeeRevision=d.revision;gate(true);}catch(e){gate(false);}finally{busy=false;}}
  function event(message){if(message.type==='offline'){gate(false);return;}last=Date.now();const revision=message.revision;window.coffeeRevision=revision;if(seen>=0&&revision!==seen){window.coffeeReviewed=false;const note=document.getElementById('admin-conflict-note');if(note)note.textContent='La disponibilidad cambió. Si tienes un borrador, vuelve a revisarlo antes de guardar.';const b=document.querySelector('button#admin-save,#admin-save button');if(b)b.disabled=true;}if(revision!==seen||!connected)snapshot();}
  if(typeof SharedWorker!=='undefined'){const worker=new SharedWorker(new URL('api/stock-worker.js',window.coffeeBase),{name:'coffee-stock'});worker.port.onmessage=e=>event(e.data);worker.port.start();window.addEventListener('beforeunload',()=>worker.port.postMessage('close'));}else{const stream=new EventSource(new URL('api/events',window.coffeeBase));stream.addEventListener('stock',e=>event({type:'stock',revision:Number(e.data)}));stream.addEventListener('heartbeat',e=>event({type:'heartbeat',revision:Number(e.data)}));stream.onerror=()=>gate(false);}
  setInterval(()=>{if(Date.now()-last>6500)gate(false);},2000);
  document.addEventListener('input',e=>{if(e.target.id==='menu-filter')filter();});document.addEventListener('change',e=>{if(e.target.id==='menu-category')filter();});
  let touched=0;function touch(e){if(!e.isTrusted||!e.target.closest('#admin-panel')||!window.coffeeCsrf||Date.now()-touched<10000)return;touched=Date.now();fetch(new URL('api/touch',window.coffeeBase),{method:'POST',headers:{'X-Coffee-CSRF':window.coffeeCsrf}}).then(r=>{if(r.status===401){window.coffeeCsrf='';const node=document.getElementById('admin-status');if(node)node.setAttribute('title','La sesión expiró; conserva el borrador e inicia sesión nuevamente');}}).catch(()=>gate(false));}
  document.addEventListener('click',e=>{if(e.isTrusted&&e.target.closest('#admin-table')&&e.target.closest('button')?.querySelector('input[type=checkbox]')){window.coffeeReviewed=false;const b=document.querySelector('button#admin-save,#admin-save button');if(b)b.disabled=true;}});
  document.addEventListener('click',touch);document.addEventListener('keydown',touch);document.addEventListener('wheel',touch,{passive:true});document.addEventListener('touchstart',touch,{passive:true});
  document.addEventListener('click',e=>{if(!connected&&e.target.closest('#chat-submit,#chat-manual,#admin-save,#admin-review')){e.preventDefault();e.stopImmediatePropagation();}},true);
  document.addEventListener('keydown',e=>{if(!connected&&e.key==='Enter'&&e.target.closest('#chat-text')){e.preventDefault();e.stopImmediatePropagation();}},true);
  const labels=new MutationObserver(()=>{document.querySelectorAll('#admin-table input[placeholder="Search..."]').forEach(el=>{el.placeholder='Buscar producto o extra';el.setAttribute('aria-label','Buscar en la tabla');});document.querySelectorAll('#admin-table button[aria-label="Add row"]').forEach(el=>el.hidden=true);});labels.observe(document.body,{childList:true,subtree:true});
  let chatSession=null,ticket=null,delivered=false,polling=false,sending=false,pendingEntry=null;
  const $=id=>document.getElementById(id);
  const messages={waiting:'El asistente está atendiendo otras consultas. Tu mensaje quedó en espera; mientras tanto, puedes explorar el menú.',running:'Déjame buscar esa información…',done:'Consulta respondida.',cancelled:'Consulta cancelada. Conservé tu texto para reintentar.',expired:'La consulta demoró más de dos minutos. Conservé tu texto; no se reenviará automáticamente.',failed:'No pude completar la consulta. Puedes reintentar o explorar el menú.',uncertain:'El asistente no está disponible por ahora. No puedo confirmar que se haya detenido; espera antes de reintentar.'};
  function status(text){if($('chat-status'))$('chat-status').textContent=text;}
  function lock(value){if($('chat-text'))$('chat-text').disabled=value;for(const id of ['chat-submit','chat-manual'])if($(id))$(id).disabled=value||!connected;}
  function append(role,text){const entry=document.createElement('div');entry.className='chat-message '+role;const body=document.createElement('div');body.className='message-text';body.textContent=text;entry.append(body);$('chat-log').append(entry);$('chat-log').scrollTop=$('chat-log').scrollHeight;return entry;}
  function clearPending(){if(pendingEntry)pendingEntry.remove();pendingEntry=null;}
  function pending(text='Déjame buscar esa información'){if(!pendingEntry){pendingEntry=append('assistant pending',text);pendingEntry.setAttribute('role','status');pendingEntry.setAttribute('aria-live','polite');}else if(pendingEntry.querySelector('.message-text').textContent!==text){pendingEntry.querySelector('.message-text').textContent=text;}}
  async function rpc(path,data){const r=await fetch(new URL(path,window.coffeeBase),data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Coffee-Client':'1'},body:JSON.stringify(data)});const value=await r.json();if(!r.ok)throw Error(value.message||'No se pudo completar la solicitud');return value;}
  async function ask(){if(!connected||ticket||sending)return;const sent=Date.now()+(window.coffeeClockOffset||0);let question=$('chat-text').value;let preference=null,budget='',compare=[];
    if(!question.trim())return;sending=true;lock(true);append('user',question);pending();status('Estoy enviando tu consulta…');try{if(!chatSession)chatSession=(await rpc('api/chat/session',{})).session_id;const answer=await rpc('api/chat/query',{session_id:chatSession,question,preference,budget,compare,submitted_at:Math.round(sent)});ticket=answer.ticket;delivered=false;if(answer.status==='waiting')pending('Tu consulta está en espera. En cuanto pueda, buscaré esa información.');status(messages[answer.status]);}catch(e){clearPending();status(e.message);lock(false);if(e.message.includes('conversación se reinició'))chatSession=null;}finally{sending=false;}}
  async function poll(){if(!ticket||polling||!connected)return;polling=true;try{const answer=await rpc('api/chat/'+chatSession+'/'+ticket);if(answer.text&&!delivered){clearPending();append('assistant',answer.text);delivered=true;}status(messages[answer.status]||'Déjame buscar esa información…');if(!delivered){if(answer.status==='running')pending();else if(answer.status==='waiting')pending('Tu consulta está en espera. En cuanto pueda, buscaré esa información.');else clearPending();}if(!answer.held){clearPending();ticket=null;lock(false);}}catch(e){status(e.message);if(e.message.includes('reinició')||e.message.includes('ya no está disponible')){clearPending();ticket=null;chatSession=null;lock(false);}}finally{polling=false;}}
  setInterval(poll,650);
  document.addEventListener('click',async e=>{const id=e.target.closest('button')?.id;if(id==='chat-submit')ask();if(id==='chat-stop'&&ticket){try{const answer=await rpc('api/chat/'+chatSession+'/'+ticket+'/cancel',{});clearPending();status(messages[answer.status]);}catch(error){status(error.message);}}if(id==='chat-reset'){if(ticket||sending){status('Espera o cancela la consulta pendiente antes de iniciar otra');return;}clearPending();chatSession=null;$('chat-log').textContent='';status('Nueva conversación. ¿Qué te gustaría consultar?');}});
  document.addEventListener('keydown',e=>{if(e.target.id==='chat-text'&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask();}});
  document.addEventListener('click',e=>{if(e.target.closest('#menu-close')){document.getElementById('menu-drawer').open=false;document.querySelector('#menu-drawer>summary').focus();}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.getElementById('menu-drawer')?.open){document.getElementById('menu-drawer').open=false;document.querySelector('#menu-drawer>summary').focus();}});
  snapshot();return [];
}
